### ISSUE TITLE
Disable the default postgres database with an env var

### ISSUE THREAD

**Issue by gravelfreeman** [vas3k/TaxHacker#9]
I would like to use my own cnpg database in my k8s cluster. I'm already setup with volsync for automatic backups and restore and gitops.

I was able to set it up but the default cnpg database from the docker image is still running in the background.

Adding an env var `POSTGRESQL_ENABLE` with `true` or `false` to make enable/disable [this](https://github.com/vas3k/TaxHacker/blob/fd6b5632cd3b5da41fd42ccc03b9d32e54d66c99/docker-compose.yml#L22-L37) part of the docker-compose

**Comment by vas3k** [comment]
Hey, @gravelfreeman!

You don't even need an env var, just edit your own docker-compose file, remove postgres container and add your DATABASE_URL there. That's actually exactly what I'm doing in production version: https://github.com/vas3k/TaxHacker/blob/main/docker-compose.production.yml

```
services:
  app:
    image: ghcr.io/vas3k/taxhacker:latest
    networks:
      - taxhacker_network
    environment:
      - NODE_ENV=production
      - **DATABASE_URL=postgresql://user@host:5432/taxhacker**
      - UPLOAD_PATH=/app/data/uploads
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  taxhacker_network:
    driver: bridge
```

(I use network "bridge" because postgres actually lives on the same machine outside docker, but you might use some external services like Supabase for that)
